services:
  - type: web
    name: the-pot-home
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        value: thepothome
      - key: NODE_ENV
        value: production
